// Sample Data for Digital Skills E-Portfolio

const sampleData = {
    curricula: [
        {
            id: 'curr-001',
            name: 'Core Surgical Training',
            specialty: 'General Surgery',
            version: '2024.1',
            effectiveDate: '2024-01-01T00:00:00.000Z',
            description: 'Core competencies for surgical trainees in years 1-3',
            procedures: [
                {
                    id: 'proc-001',
                    code: 'SURG-001',
                    name: 'Appendectomy',
                    category: 'Emergency Surgery',
                    subcategory: 'Abdominal',
                    description: 'Surgical removal of the appendix',
                    skillLevels: [
                        { level: 'Observed', description: 'Watched procedure being performed', requiredCases: 3 },
                        { level: 'Assisted', description: 'Assisted in procedure', requiredCases: 5 },
                        { level: 'Supervised', description: 'Performed under direct supervision', requiredCases: 8 },
                        { level: 'Independent', description: 'Performed independently', requiredCases: 10 }
                    ],
                    theoryRequired: true,
                    practiceRequired: true,
                    minimumCases: 10,
                    minimumLevel: 'Supervised',
                    estimatedDuration: 60,
                    difficulty: 'Intermediate',
                    prerequisites: [],
                    references: ['https://example.com/appendectomy-guide']
                },
                {
                    id: 'proc-002',
                    code: 'SURG-002',
                    name: 'Hernia Repair',
                    category: 'Elective Surgery',
                    subcategory: 'Abdominal',
                    description: 'Surgical repair of inguinal or umbilical hernia',
                    skillLevels: [
                        { level: 'Observed', description: 'Watched procedure being performed', requiredCases: 2 },
                        { level: 'Assisted', description: 'Assisted in procedure', requiredCases: 4 },
                        { level: 'Supervised', description: 'Performed under direct supervision', requiredCases: 6 },
                        { level: 'Independent', description: 'Performed independently', requiredCases: 8 }
                    ],
                    theoryRequired: true,
                    practiceRequired: true,
                    minimumCases: 8,
                    minimumLevel: 'Supervised',
                    estimatedDuration: 90,
                    difficulty: 'Intermediate',
                    prerequisites: [],
                    references: []
                },
                {
                    id: 'proc-003',
                    code: 'SURG-003',
                    name: 'Cholecystectomy (Laparoscopic)',
                    category: 'Elective Surgery',
                    subcategory: 'Hepatobiliary',
                    description: 'Laparoscopic removal of the gallbladder',
                    skillLevels: [
                        { level: 'Observed', description: 'Watched procedure being performed', requiredCases: 5 },
                        { level: 'Assisted', description: 'Assisted in procedure', requiredCases: 8 },
                        { level: 'Supervised', description: 'Performed under direct supervision', requiredCases: 12 },
                        { level: 'Independent', description: 'Performed independently', requiredCases: 15 }
                    ],
                    theoryRequired: true,
                    practiceRequired: true,
                    minimumCases: 15,
                    minimumLevel: 'Supervised',
                    estimatedDuration: 120,
                    difficulty: 'Advanced',
                    prerequisites: ['proc-001'],
                    references: []
                },
                {
                    id: 'proc-004',
                    code: 'SURG-004',
                    name: 'Central Line Insertion',
                    category: 'Emergency Procedures',
                    subcategory: 'Vascular Access',
                    description: 'Insertion of central venous catheter',
                    skillLevels: [
                        { level: 'Observed', description: 'Watched procedure being performed', requiredCases: 2 },
                        { level: 'Assisted', description: 'Assisted in procedure', requiredCases: 3 },
                        { level: 'Supervised', description: 'Performed under direct supervision', requiredCases: 5 },
                        { level: 'Independent', description: 'Performed independently', requiredCases: 10 }
                    ],
                    theoryRequired: true,
                    practiceRequired: true,
                    minimumCases: 10,
                    minimumLevel: 'Independent',
                    estimatedDuration: 30,
                    difficulty: 'Intermediate',
                    prerequisites: [],
                    references: []
                },
                {
                    id: 'proc-005',
                    code: 'SURG-005',
                    name: 'Bowel Resection',
                    category: 'Elective Surgery',
                    subcategory: 'Colorectal',
                    description: 'Surgical resection of bowel segment',
                    skillLevels: [
                        { level: 'Observed', description: 'Watched procedure being performed', requiredCases: 5 },
                        { level: 'Assisted', description: 'Assisted in procedure', requiredCases: 10 },
                        { level: 'Supervised', description: 'Performed under direct supervision', requiredCases: 15 },
                        { level: 'Independent', description: 'Performed independently', requiredCases: 20 }
                    ],
                    theoryRequired: true,
                    practiceRequired: true,
                    minimumCases: 20,
                    minimumLevel: 'Supervised',
                    estimatedDuration: 180,
                    difficulty: 'Complex',
                    prerequisites: ['proc-001', 'proc-002'],
                    references: []
                }
            ],
            createdAt: '2024-01-01T00:00:00.000Z',
            updatedAt: '2024-01-01T00:00:00.000Z'
        }
    ],

    supervisors: [
        {
            id: 'sup-001',
            email: 'dr.smith@hospital.com',
            password: 'supervisor123',
            firstName: 'James',
            lastName: 'Smith',
            role: 'supervisor',
            title: 'Consultant Surgeon',
            specialty: 'General Surgery',
            hospitalId: 'hosp-001',
            certifications: ['FRCS', 'MBBS', 'Advanced Laparoscopic Surgery'],
            yearsOfExperience: 15,
            createdAt: '2023-01-15T00:00:00.000Z',
            updatedAt: '2024-01-15T00:00:00.000Z',
            bio: 'Experienced consultant surgeon specializing in general and laparoscopic surgery'
        },
        {
            id: 'sup-002',
            email: 'dr.johnson@hospital.com',
            password: 'supervisor123',
            firstName: 'Sarah',
            lastName: 'Johnson',
            role: 'supervisor',
            title: 'Senior Consultant',
            specialty: 'General Surgery',
            hospitalId: 'hosp-001',
            certifications: ['FRCS', 'MBBS', 'Colorectal Surgery'],
            yearsOfExperience: 20,
            createdAt: '2022-06-01T00:00:00.000Z',
            updatedAt: '2024-01-15T00:00:00.000Z',
            bio: 'Senior consultant with expertise in colorectal and emergency surgery'
        }
    ],

    doctors: [
        {
            id: 'doc-001',
            email: 'dr.brown@hospital.com',
            password: 'doctor123',
            firstName: 'Emily',
            lastName: 'Brown',
            role: 'doctor',
            specialty: 'General Surgery',
            yearOfTraining: 2,
            hospitalId: 'hosp-001',
            supervisors: ['sup-001', 'sup-002'],
            curriculumId: 'curr-001',
            createdAt: '2023-08-01T00:00:00.000Z',
            updatedAt: '2024-01-15T00:00:00.000Z',
            bio: 'CT2 surgical trainee with interest in laparoscopic techniques'
        },
        {
            id: 'doc-002',
            email: 'dr.wilson@hospital.com',
            password: 'doctor123',
            firstName: 'Michael',
            lastName: 'Wilson',
            role: 'doctor',
            specialty: 'General Surgery',
            yearOfTraining: 1,
            hospitalId: 'hosp-001',
            supervisors: ['sup-001'],
            curriculumId: 'curr-001',
            createdAt: '2024-08-01T00:00:00.000Z',
            updatedAt: '2024-08-01T00:00:00.000Z',
            bio: 'CT1 surgical trainee starting core training'
        }
    ],

    verifications: [
        {
            id: 'ver-001',
            doctorId: 'doc-001',
            supervisorId: 'sup-001',
            procedureId: 'proc-001',
            requestId: 'req-old-001',
            skillLevel: 'Assisted',
            rating: 4,
            datePerformed: '2024-09-15T00:00:00.000Z',
            dateVerified: '2024-09-16T00:00:00.000Z',
            supervisorNotes: 'Good understanding of anatomy. Need to work on speed and efficiency. Overall solid performance.',
            doctorNotes: 'Emergency appendectomy, patient age 32, uncomplicated case',
            patientAge: 32,
            patientSex: 'F',
            location: 'OR-3',
            urgency: 'Emergency',
            complications: null,
            areasOfStrength: ['Anatomical knowledge', 'Patient communication'],
            areasForImprovement: ['Speed', 'Instrument handling'],
            followUpRequired: false,
            createdAt: '2024-09-16T00:00:00.000Z',
            updatedAt: '2024-09-16T00:00:00.000Z'
        },
        {
            id: 'ver-002',
            doctorId: 'doc-001',
            supervisorId: 'sup-001',
            procedureId: 'proc-001',
            requestId: 'req-old-002',
            skillLevel: 'Assisted',
            rating: 4,
            datePerformed: '2024-10-02T00:00:00.000Z',
            dateVerified: '2024-10-03T00:00:00.000Z',
            supervisorNotes: 'Improved technique. Better instrument handling. Ready to progress to supervised level.',
            doctorNotes: 'Routine appendectomy with minimal complications',
            patientAge: 45,
            patientSex: 'M',
            location: 'OR-2',
            urgency: 'Urgent',
            complications: null,
            areasOfStrength: ['Technique', 'Decision making'],
            areasForImprovement: ['Documentation'],
            followUpRequired: false,
            createdAt: '2024-10-03T00:00:00.000Z',
            updatedAt: '2024-10-03T00:00:00.000Z'
        },
        {
            id: 'ver-003',
            doctorId: 'doc-001',
            supervisorId: 'sup-002',
            procedureId: 'proc-001',
            requestId: 'req-old-003',
            skillLevel: 'Supervised',
            rating: 5,
            datePerformed: '2024-10-20T00:00:00.000Z',
            dateVerified: '2024-10-21T00:00:00.000Z',
            supervisorNotes: 'Excellent performance. Performed independently with minimal supervision. Ready for more complex cases.',
            doctorNotes: 'Perforated appendicitis, required careful technique',
            patientAge: 28,
            patientSex: 'M',
            location: 'OR-1',
            urgency: 'Emergency',
            complications: 'Peritoneal contamination managed appropriately',
            areasOfStrength: ['Technical skill', 'Problem solving', 'Communication'],
            areasForImprovement: [],
            followUpRequired: false,
            createdAt: '2024-10-21T00:00:00.000Z',
            updatedAt: '2024-10-21T00:00:00.000Z'
        },
        {
            id: 'ver-004',
            doctorId: 'doc-001',
            supervisorId: 'sup-001',
            procedureId: 'proc-002',
            requestId: 'req-old-004',
            skillLevel: 'Assisted',
            rating: 3,
            datePerformed: '2024-09-28T00:00:00.000Z',
            dateVerified: '2024-09-29T00:00:00.000Z',
            supervisorNotes: 'First hernia repair. Good theoretical knowledge. Need more practice with mesh placement.',
            doctorNotes: 'Inguinal hernia repair with mesh',
            patientAge: 55,
            patientSex: 'M',
            location: 'OR-4',
            urgency: 'Routine',
            complications: null,
            areasOfStrength: ['Theory knowledge'],
            areasForImprovement: ['Mesh placement', 'Knot tying'],
            followUpRequired: true,
            createdAt: '2024-09-29T00:00:00.000Z',
            updatedAt: '2024-09-29T00:00:00.000Z'
        },
        {
            id: 'ver-005',
            doctorId: 'doc-001',
            supervisorId: 'sup-001',
            procedureId: 'proc-004',
            requestId: 'req-old-005',
            skillLevel: 'Supervised',
            rating: 4,
            datePerformed: '2024-11-01T00:00:00.000Z',
            dateVerified: '2024-11-02T00:00:00.000Z',
            supervisorNotes: 'Good ultrasound guidance. Proper sterile technique. One attempt successful.',
            doctorNotes: 'Central line insertion for septic patient',
            patientAge: 67,
            patientSex: 'F',
            location: 'ICU',
            urgency: 'Urgent',
            complications: null,
            areasOfStrength: ['Ultrasound guidance', 'Sterile technique'],
            areasForImprovement: ['Speed under pressure'],
            followUpRequired: false,
            createdAt: '2024-11-02T00:00:00.000Z',
            updatedAt: '2024-11-02T00:00:00.000Z'
        }
    ],

    requests: [
        {
            id: 'req-001',
            doctorId: 'doc-001',
            supervisorId: 'sup-001',
            procedureId: 'proc-001',
            requestedLevel: 'Supervised',
            status: 'Pending',
            datePerformed: '2024-11-20T00:00:00.000Z',
            patientAge: 38,
            patientSex: 'F',
            notes: 'Emergency appendectomy performed independently. Patient had uncomplicated acute appendicitis. Procedure completed in 55 minutes with good outcome.',
            location: 'OR-2',
            urgency: 'Emergency',
            complications: null,
            createdAt: '2024-11-20T12:00:00.000Z',
            updatedAt: '2024-11-20T12:00:00.000Z',
            expiresAt: '2024-12-20T12:00:00.000Z'
        },
        {
            id: 'req-002',
            doctorId: 'doc-001',
            supervisorId: 'sup-002',
            procedureId: 'proc-002',
            requestedLevel: 'Assisted',
            status: 'Pending',
            datePerformed: '2024-11-18T00:00:00.000Z',
            patientAge: 42,
            patientSex: 'M',
            notes: 'Assisted in inguinal hernia repair. Helped with mesh placement and closure. Good understanding of anatomy.',
            location: 'OR-1',
            urgency: 'Routine',
            complications: null,
            createdAt: '2024-11-18T16:00:00.000Z',
            updatedAt: '2024-11-18T16:00:00.000Z',
            expiresAt: '2024-12-18T16:00:00.000Z'
        },
        {
            id: 'req-003',
            doctorId: 'doc-002',
            supervisorId: 'sup-001',
            procedureId: 'proc-001',
            requestedLevel: 'Observed',
            status: 'Pending',
            datePerformed: '2024-11-21T00:00:00.000Z',
            patientAge: 29,
            patientSex: 'M',
            notes: 'Observed appendectomy from start to finish. First exposure to emergency abdominal surgery.',
            location: 'OR-3',
            urgency: 'Emergency',
            complications: null,
            createdAt: '2024-11-21T10:00:00.000Z',
            updatedAt: '2024-11-21T10:00:00.000Z',
            expiresAt: '2024-12-21T10:00:00.000Z'
        }
    ]
};

// Initialize data store with sample data when script loads
if (typeof dataStore !== 'undefined') {
    dataStore.initialize(sampleData);
}
